apiVersion: apperator.simone.sh/v1alpha1
Kind: app
metadata:
  name: plex
  namespace: plex
spec:
  create_namespace: True
  containers:
  - image: plexinc/pms-docker
    hostVolumes:
    - /opt/k3s/plex/plex-config:/plex
    - /opt/k3s/plex/plex-transcode:/transcode
    - /opt/k3s/plex/plex-data:/data
    resources:
      memory: 512Mi-1024Mi
      cpu: 0.5-1
    livenessProbe:
      httpGet:
        path: /
        port: 8112
      initialDelaySeconds: 30
      periodSeconds: 30
    readinessProbe:
      httpGet:
        path: /
        port: 8113
      initialDelaySeconds: 30
      periodSeconds: 30

  ingress:
  - hostname: plex.simone.sh
    targetPort: 32400
  env:
    PLEX_CLAIM: "blabla"  # https://www.plex.tv/claim
